// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteConnection(arg1:number):Promise<void>;

export function LoadConnections():Promise<Array<models.Server>>;

export function SaveConnection(arg1:models.Server):Promise<void>;

export function StartSSHForward(arg1:number):Promise<void>;

export function StopSSHForward(arg1:number):Promise<void>;

export function UpdateConnection(arg1:models.Server):Promise<void>;
