// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function LoadConnections() {
  return window['go']['main']['App']['LoadConnections']();
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function StartSSHForward(arg1) {
  return window['go']['main']['App']['StartSSHForward'](arg1);
}

export function StopSSHForward(arg1) {
  return window['go']['main']['App']['StopSSHForward'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}
