name: Build & Release Wails (Native Per OS)

on:
  push:
    tags:
      - "*" # Trigger saat ada tag baru

permissions:
  contents: write

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "SSHPortForwads"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "SSHPortForwads"
            platform: "windows/amd64"
            os: "windows-latest"
          - name: "SSHPortForwads"
            platform: "darwin/universal"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          if ($Env:RUNNER_OS -eq "Windows") {
            Remove-Item -Recurse -Force node_modules, package-lock.json
          } elseif ($Env:RUNNER_OS -eq "macOS" -or $Env:RUNNER_OS -eq "Linux") {
            rm -rf node_modules package-lock.json
          }
          npm install
        working-directory: ./frontend
        shell: pwsh

      - name: Build Wails App
        uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.23.3"
          package: true # penting agar menghasilkan file yang bisa dirilis

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
